### ISSUE TITLE
Trivia Screen Enhancement.

### ISSUE THREAD

**Issue by Nahom-ab** [Nahom-ab/aad-team-11-animation-challenge#13]
### This screen is 70% done as opposed to the **Prototype Design**. we just need to add:

- [x] Timer Progress Bar seen on the prototype. this seems challenging but if any one want to do it. it would be an awesome feature to have.

- [x] Adding the Questions counter text as next questions progress.

## ProtoType Screen:
![Trivia Screen](https://user-images.githubusercontent.com/47426814/67039157-775c4680-f129-11e9-93e3-3369186b5a71.png)

## Actual Design Now:
![3](https://user-images.githubusercontent.com/47426814/67039589-52b49e80-f12a-11e9-9b14-f82e0b1e9181.png)

**Comment by EyuCoder** [comment]
i want this one

**Comment by Nahom-ab** [comment]
@elysium09 , okay you got it,  the custom timer progress bar is left to do.  think animated vectors.
