### ISSUE TITLE
Welcome Screen to Categories Screen Transition Animations.

### ISSUE THREAD

**Issue by Nahom-ab** [Nahom-ab/aad-team-11-animation-challenge#16]
### Applying Transitions Animations when a user clicks " Choose Category " to navigate to the Category Screen ( CategoryActivity ).

 I have posted on slack some animations ideas to apply to transitions and others. Please check those out for a starting point.

**Comment by abdulbytes** [comment]
@Nahom-ab i want to work on this, if no is.

**Comment by Nahom-ab** [comment]
okay, its yours..
