### ISSUE TITLE
Category Screen to Trivia Screen Transition Animation.

### ISSUE THREAD

**Issue by Nahom-ab** [Nahom-ab/aad-team-11-animation-challenge#17]
### Applying Transition Animation when a user clicks on one of the categories to navigate to the Trivia Screen ( TriviaActivity ).

I have posted on slack some animations ideas to apply to transitions and others. Please check those out for a starting point.

**Comment by kidus-worku** [comment]
I got this, and also the timer.

**Comment by Nahom-ab** [comment]
okay, you got it, i think joel wanted the UI part of the trivia screen enhancement. which includes the timer.but you guys should talk and decide that.
